name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 17
        cache: yarn

    - name: Yarn Install
      run: yarn install

    - name: Cache Vue Build
      uses: actions/cache@v3.0.4
      id: build-cache
      with:
        path: dist
        key: client-build-${{ hashFiles('public', 'src') }}

    - name: Build Vue Project
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: |
          tyranozomby/mamidou
        tags: |
          type=sha,prefix=
          latest

    - name: Build and push image
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
